name: goe
favicon: null
layout_spectrum: 0.4098881362006068
typography_spectrum: 0.63417
title: goe page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#271412'
    - '#000000'
    - '#bb0a13'
    - '#ff0000'
    - '#550000'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
