name: goe
favicon: null
layout_spectrum: 0.42907
typography_spectrum: 0.63352
title: goe page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c0'
    - '#9f9d9e'
    - '#888483'
    - '#706762'
    - '#524612'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
